### ISSUE TITLE
Split payment amount 1.6.1.24

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop-1.6#15]
Hi,

We have a payment issue on the shop. This happens whatever the payment method, being Payzen or Paypal.

When a customer places an order, the order value sent to payment portal is randomly reduced. The customer pays then only part of the order.

The successful payment comes back to the shop and the order is created, logging the reduced amount paid.

When we change the order status to "order being prepared", a new line is automatically added in the order payment log with the missing amount. But it has never been paid. It's just Prestashop that adds this line.

This happens randomly, not to every order.

Thanks

![Screen Shot 2021-01-04 at 11 34 05](https://user-images.githubusercontent.com/71735/105688810-f24a0a80-5ef1-11eb-9c78-51e17945f415.png)
![Screen Shot 2021-01-06 at 17 47 05](https://user-images.githubusercontent.com/71735/105688814-f413ce00-5ef1-11eb-9910-a147ee3f99e5.png)

**Comment by matks** [comment]
As this [Pull Request from @kpodemski, maintainer of this repository](https://github.com/PrestaShop/PrestaShop-1.6/pull/25), explains: this repository did its job by releasing a PrestaShop 1.6 version compatible for PHP 7.2 and provided a few security fixes. It's now time to let 1.6 live in peace as an archived repository.
