### ISSUE TITLE
Is it safe to upgrade PHP to 7.2

### ISSUE THREAD

**Issue by projectmb** [PrestaShop/PrestaShop-1.6#22]
Is it safe to upgrade PHP to 7.2, do I need some specific version/commits for this?

**Comment by ghost** [comment]
@projectmb, the master branch is compatible with PHP 7.2 and you may also try PHP 7.3 which was compatible during our tests.
More details on : https://github.com/PrestaShop/PrestaShop-1.6/pull/4

Make sure to always upgrade and test your website on a development environment first, some third party modules might not be compatible with PHP 7.2/7.3 and my need adjustments.

**Comment by matks** [comment]
As this [Pull Request from @kpodemski, maintainer of this repository](https://github.com/PrestaShop/PrestaShop-1.6/pull/25), explains: this repository did its job by releasing a PrestaShop 1.6 version compatible for PHP 7.2 and provided a few security fixes. It's now time to let 1.6 live in peace as an archived repository.
