### ISSUE TITLE
Prestashop 1.6 alternative supporting php 7.4 (and php8)

### ISSUE THREAD

**Issue by kintaro1981** [PrestaShop/PrestaShop-1.6#24]
If you need it "Thirtybees" is a compatible 1.6 prestashop alternative actively developed.

https://github.com/thirtybees/thirtybees
https://forum.thirtybees.com/

**Comment by kpodemski** [comment]
There's no need to promote alternatives to 1.6, there's PrestaShop 8.0 available :)

**Comment by kintaro1981** [comment]
Is Prestashop 8.0 a ps1.6 compatible with php 7.4? I’m not promoting, I noticed people asking for p.s.1.6 with php7.4+ support and I though to give them this information.
