### ISSUE TITLE
Longstanding bug still there [PSCSX-9685] Entering wrong information into invoice

### ISSUE THREAD

**Issue by ukbazz** [PrestaShop/PrestaShop-1.6#6]
It seems an issue first reported on the old Forge repository is still 'live' I can no longer access Forge bug repository and it is not mentioned here,
But the issue occurs while creating new account on OPC with a separarate delivery and invoice addresses. 

Missing out any fields in the 2n'd 'Invoice Address  the registration takes place on the delivery address and the Invoice address will not be made.

Is there a fix for this?

**Comment by olecorre** [comment]
Sorry but 1.6 is no longer supported, no more requests are processed. The request must be in the old forge https://github.com/PrestaShop/PrestaShop/issues
