### ISSUE TITLE
Bug in OPC when adding separate invoice address

### ISSUE THREAD

**Issue by ukbazz** [PrestaShop/PrestaShop-1.6#7]
It seems an issue first reported on the old Forge repository is still 'live' I can no longer access Forge bug repository and it is not mentioned here,
But the issue occurs while creating new account on OPC with a separate delivery and invoice addresses.

Missing out any fields in the 2n'd 'Invoice Address the registration takes place on the delivery address and the Invoice address will not be made.

Is there a fix for this?
Using Prestashop v 1.6.1.24

**Comment by ghost** [comment]
This version is end of life. 
Only security issue and php version are accepted

**Comment by Max84** [comment]
As @okom3pom told, so I close this issue, sorry for that.
