### ISSUE TITLE
JS error : Uncaught TypeError: combinationsJS[k].idsAttributes is undefined

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop-1.6#9]
On some product page without combination, I have following in JS debug console:
 
`Uncaught TypeError: combinationsJS[k].idsAttributes is undefined`

Targeting to this file/line: https://github.com/PrestaShop/PrestaShop-1.6/blob/70d12a5ffbd9f1123e76cded1be8d2f78d5f015c/themes/default-bootstrap/js/product.js#L109

PS 1.6.1.24 + PHP 7.1 + nginx
Cache + JS smart cache + combinations enabled

**Comment by Max84** [comment]
Thanks for this report and PR. Anyone can use it if needed, but this version is end of life.
Only security issue and php version are accepted for merged.
